-- Schema: Base
-- Prefix: BA_

CREATE TABLE BA_SystemCodeType
(
	SystemCodeTypeID	BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	SystemCodeTypeName	VARCHAR(250) NOT NULL,
	SystemCodeTypeNote	VARCHAR(250) NOT NULL,
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_SystemCodeType PRIMARY KEY(SystemCodeTypeID)
);

CREATE TABLE BA_SystemCodeValue
(
	SystemCodeValueID	BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	SystemCodeTypeID	BIGINT NOT NULL,
	SystemCodeValue		VARCHAR(2000) NOT NULL,
	SystemCodeAbbrev	VARCHAR(50),
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_SystemCodeValue PRIMARY KEY(SystemCodeValueID)
	
);

CREATE TABLE BA_SystemTable
(
	SystemTableID	BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	SystemTableName	VARCHAR(250) NOT NULL,
	SystemTableNote	VARCHAR(250) NOT NULL,	
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_SystemTable PRIMARY KEY(SystemTableID)
);

CREATE TABLE BA_Menu
(
	MenuID			BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	MenuName		VARCHAR(250) NOT NULL,
	Url				VARCHAR(500) NOT NULL,	
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_Menu PRIMARY KEY (MenuID)
);

CREATE TABLE BA_MenuItem
(
	MenuItemID		BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	MenuID			BIGINT NOT NULL,
	MenuItemName	VARCHAR(250) NOT NULL,
	Url				VARCHAR(500) NOT NULL,
	OrderBy			INT,
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_MenuItem PRIMARY KEY(MenuItemID)
);

CREATE TABLE BA_SubMenu
(
	SubMenuID		BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	ChildMenuItemID		BIGINT NOT NULL,
	ParentMenuItemID BIGINT NOT NULL,
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_SubMenu PRIMARY KEY(SubMenuID)
);

CREATE TABLE BA_MenuItemComponentMap
(
	MenuItemComponentMapID	BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	MenuItemID		BIGINT NOT NULL,
	ComponentID		BIGINT NOT NULL,
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_MenuItemComponentMap PRIMARY KEY(MenuItemComponentMapID)
);

CREATE TABLE BA_Message
(
	MessageID		BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	SendingApplicationUserID	BIGINT NOT NULL,
	ReceivingApplicationUserID	BIGINT,
	Subject			VARCHAR(250) NOT NULL,
	MessageBody		TEXT NOT NULL,
	MessageStatusCode BIGINT NOT NULL,
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_Message PRIMARY KEY(MessageID)
);

CREATE TABLE BA_MessageThread
(
	MessageThreadID	BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	ChildMessageID	BIGINT NOT NULL,
	ParentMessageID	BIGINT NOT NULL,
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_BA_MessageThread PRIMARY KEY(MessageThreadID)
);


