-- Schema:	Entity
-- Prefix:	EN_

CREATE TABLE EN_Person 
(
	PersonID		BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	FirstName		VARCHAR(100) NOT NULL,
	MiddleName		VARCHAR(100),
	LastName		VARCHAR(100) NOT NULL,
	Prefix			VARCHAR(10),
	Suffix			VARCHAR(20),
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_EN_Person PRIMARY KEY (PersonID)
	
);

CREATE TABLE EN_Address
(
	AddressID		BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	AddressTypeCode	BIGINT NOT NULL,
	Street1			VARCHAR(250) NOT NULL,
	Street2			VARCHAR(250),
	Street3			VARCHAR(250),
	City			VARCHAR(100),
	Region			BIGINT NOT NULL,
	PostalCode		BIGINT NOT NULL,
	CountryCode		BIGINT NOT NULL,
	PersonID		BIGINT NOT NULL,
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_EN_Address PRIMARY KEY (AddressID)
	
);

CREATE TABLE EN_Contact
(
	ContactID		BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	ContactTypeCode	BIGINT NOT NULL,
	ContactValue	VARCHAR(250) NOT NULL,
	PersonID		BIGINT NOT NULL,
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_EN_Contact PRIMARY KEY (ContactID)
);

CREATE TABLE EN_ApplicationUser
(
	ApplicationUserID	BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY(INCREMENT 1 START 1),
	PersonID			BIGINT NOT NULL,
	Username			VARCHAR(100) NOT NULL,
	Password			VARCHAR(100) NOT NULL,
	UserTypeCode		BIGINT NOT NULL,
	UserStatusCode		BIGINT NOT NULL,
	ResetPasswordFlag	CHAR(1) NOT NULL,
	ResetPasswordToken	VARCHAR(100),
	CreatedDate		TIMESTAMP NOT NULL,
	CreatedUserID	BIGINT NOT NULL,
	ModifiedDate	TIMESTAMP NOT NULL,
	ModifiedUserID	BIGINT NOT NULL,
	ActiveFlag		CHAR(1) NOT NULL,
	CONSTRAINT PK_EN_ApplicationUser PRIMARY KEY (ApplicationUserID)
);
